### ISSUE TITLE
Add nebari colors' hex values to this repo

### ISSUE THREAD

**Issue by pavithraes** [nebari-dev/nebari-design#4]
### Context

It'll be helpful to have the nebari brand colors shared here for quick access. :)

Nebari colors:
- Yellow: #EAB54E
- Green: #20AAA1
- Black: #0F1015
- Purple: #BA18DA

### Value and/or benefit

Besides the logos, folks may also like to use the brand colors for diagrams, presentations, etc. when they refer to Nebari.

### Anything else?

Maybe we can share this list in the README itself?

**Comment by pavithraes** [comment]
@trallard What do you think about this? I'll open a PR proactively, but please feel free to close them if you had other ideas in mind!

I'd also appreciate it if you can help add relevant issue labels here, I don't have permissions to add them. :)

**Comment by trallard** [comment]
Hey @pavithraes  I think this is a great idea + would be good to also add details on our fonts: Atkinson Hyperlegible and Poppins

**Comment by pavithraes** [comment]
> would be good to also add details on our fonts

Oh yes, thanks! Added to the PR!
